# Generated by Django 6.0.4 on 2026-04-29 06:30

import django.db.models.deletion
import music.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=music.models.branding_path)),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to=music.models.branding_path)),
                ('watermark', models.ImageField(blank=True, null=True, upload_to=music.models.branding_path)),
                ('show_on_player', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Branding',
            },
        ),
        migrations.CreateModel(
            name='TrendingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('track', 'Track'), ('artist', 'Artist'), ('album', 'Album')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('single', 'Single'), ('compilation', 'Compilation')], default='album', max_length=20),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='album',
            name='plays_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='monthly_listeners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='social_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='social_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='social_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='trend_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.CharField(blank=True, default='🎵', max_length=10),
        ),
        migrations.AddField(
            model_name='musiccomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.track_cover_path),
        ),
        migrations.AddField(
            model_name='track',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_on', to='music.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_song_of_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, help_text='ISRC code', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='mastered_by',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='mixed_by',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='produced_by',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='recorded_at',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='trend_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='track',
            name='written_by',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to=music.models.album_cover_path),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.artist_photo_path),
        ),
        migrations.AlterField(
            model_name='musiccomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to=music.models.track_audio_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.track_cover_path),
        ),
        migrations.CreateModel(
            name='TrackLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'track')},
            },
        ),
    ]
