# Generated by Django 6.0.4 on 2026-04-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_platformbranding_trendingsnapshot_album_album_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
