# Generated by Django 4.2.30 on 2026-06-16 06:32

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_uploaded_by_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.album_cover_path),
        ),
    ]
