# Generated by Django 4.2.30 on 2026-06-17 07:08

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, help_text='External link to the audio file (used instead of an upload to save storage space).'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=music.models.track_audio_path),
        ),
    ]
