# Generated by Django 4.2.30 on 2026-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_track_audio_url_alter_track_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics_lrc',
            field=models.TextField(blank=True, help_text='Timestamped LRC format e.g. [00:12.50] Line of lyrics'),
        ),
    ]
