# Generated by Django 4.2.30 on 2026-05-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='observabili_user_id_71768c_idx',
            old_name='obs_audit_user_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='observabili_action_00abe0_idx',
            old_name='obs_audit_action_idx',
        ),
    ]
