# Generated by Django 6.0.4 on 2026-04-20 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('image', 'Image'), ('url', 'URL'), ('bool', 'Boolean'), ('color', 'Color')], default='text', max_length=20)),
                ('group', models.CharField(default='general', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AIGeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image_url', models.URLField(max_length=1000)),
                ('local_file', models.ImageField(blank=True, null=True, upload_to='ai_generated/')),
                ('saved_to_platform', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('model_used', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
