# Generated by Django 4.2.30 on 2026-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailconfig_gatewayconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='password',
            field=models.CharField(blank=True, help_text='App password or API key', max_length=500),
        ),
        migrations.AlterField(
            model_name='gatewayconfig',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Gateway-specific: bank_name, account_no, routing_no, etc.'),
        ),
    ]
