from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NEXUS', max_length=100)),
                ('site_tagline', models.CharField(blank=True, max_length=300)),
                ('site_description', models.TextField(blank=True)),
                ('logo_primary', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('logo_footer', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('logo_email', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('social_preview', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.TextField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('social_tiktok', models.URLField(blank=True)),
                ('social_discord', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, default='© {year} NEXUS. All rights reserved.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Branding Config'},
        ),
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6c47ff', max_length=20)),
                ('secondary_color', models.CharField(default='#ff4778', max_length=20)),
                ('accent_color', models.CharField(default='#00d4aa', max_length=20)),
                ('background_color', models.CharField(default='#080810', max_length=20)),
                ('surface_color', models.CharField(default='#13132a', max_length=20)),
                ('text_primary', models.CharField(default='#e8e8f0', max_length=20)),
                ('text_secondary', models.CharField(default='#8888aa', max_length=20)),
                ('heading_font', models.CharField(default='Syne', max_length=100)),
                ('body_font', models.CharField(default='DM Sans', max_length=100)),
                ('heading_font_url', models.URLField(blank=True)),
                ('body_font_url', models.URLField(blank=True)),
                ('base_font_size', models.CharField(default='16px', max_length=10)),
                ('border_radius', models.CharField(default='12px', max_length=10)),
                ('max_width', models.CharField(default='1380px', max_length=10)),
                ('btn_radius', models.CharField(default='8px', max_length=10)),
                ('btn_primary_bg', models.CharField(default='#6c47ff', max_length=20)),
                ('btn_primary_text', models.CharField(default='#ffffff', max_length=20)),
                ('default_mode', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=10)),
                ('custom_css', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Theme Config'},
        ),
        migrations.CreateModel(
            name='GlobalSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='NEXUS — Media Platform', max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/seo/')),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=30)),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('canonical_domain', models.CharField(blank=True, max_length=200)),
                ('allow_indexing', models.BooleanField(default=True)),
                ('robots_txt', models.TextField(default='User-agent: *\nAllow: /\nDisallow: /admin-panel/\nDisallow: /auth/\n')),
                ('schema_org_type', models.CharField(default='WebSite', max_length=50)),
                ('google_site_verification', models.CharField(blank=True, max_length=200)),
                ('bing_site_verification', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Global SEO'},
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/seo/pages/')),
                ('no_index', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero','Hero Banner'),('featured','Featured Content'),('cta','Call to Action'),('stats','Statistics'),('testimonials','Testimonials'),('faq','FAQ'),('pricing','Pricing'),('partners','Partners / Logos'),('newsletter','Newsletter Signup'),('custom','Custom HTML Block')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/homepage/')),
                ('video_url', models.URLField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('cta2_text', models.CharField(blank=True, max_length=100)),
                ('cta2_url', models.CharField(blank=True, max_length=300)),
                ('bg_color', models.CharField(blank=True, max_length=20)),
                ('text_color', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['order'], 'verbose_name': 'Homepage Section'},
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('primary','Primary Navigation'),('footer','Footer Menu'),('footer2','Footer Column 2'),('footer3','Footer Column 3'),('sidebar','Sidebar Menu'),('mobile','Mobile Menu'),('user','User Dropdown')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('requires_login', models.BooleanField(default=False)),
                ('requires_admin', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft','Draft'),('published','Published')], default='draft', max_length=20)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('show_in_nav', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_type', models.CharField(choices=[('banner','Top Banner Bar'),('promo','Promo Bar'),('popup','Modal Popup'),('notice','Site-Wide Notice')], default='banner', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('bg_color', models.CharField(default='#6c47ff', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissible', models.BooleanField(default=True)),
                ('show_to_logged_in', models.BooleanField(default=True)),
                ('show_to_guests', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('welcome','Welcome Email'),('password_reset','Password Reset'),('email_verification','Email Verification'),('subscription_confirm','Subscription Confirmed'),('payment_receipt','Payment Receipt'),('content_approved','Content Approved'),('content_rejected','Content Rejected'),('payout_processed','Payout Processed'),('creator_welcome','Creator Welcome'),('admin_alert','Admin Alert'),('custom','Custom Template')], max_length=30, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('position', models.CharField(choices=[('head','Inside <head>'),('body_start','After <body> open'),('body_end','Before </body>')], default='head', max_length=20)),
                ('script', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('load_on_pages', models.CharField(blank=True, default='*', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['position', 'order']},
        ),
        migrations.CreateModel(
            name='MaintenanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(default='Under Maintenance', max_length=200)),
                ('message', models.TextField(default="We are performing scheduled maintenance. We'll be back shortly.")),
                ('estimated_return', models.DateTimeField(blank=True, null=True)),
                ('allow_admins', models.BooleanField(default=True)),
                ('allowed_ips', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Maintenance Config'},
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('rollout_pct', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('cta','CTA Block'),('banner','Banner'),('testimonial','Testimonial'),('feature','Feature Grid Item'),('info_card','Info Card'),('faq_item','FAQ Item'),('stat','Statistic'),('partner','Partner Logo')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/blocks/')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['order', 'name']},
        ),
    ]
