# Generated by Django 4.2.30 on 2026-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingconfig',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Logo for light backgrounds', null=True, upload_to='cms/branding/'),
        ),
        migrations.AlterField(
            model_name='brandingconfig',
            name='logo_primary',
            field=models.ImageField(blank=True, help_text='Primary logo (dark bg)', null=True, upload_to='cms/branding/'),
        ),
        migrations.AlterField(
            model_name='brandingconfig',
            name='social_preview',
            field=models.ImageField(blank=True, help_text='Default OG image (1200x630)', null=True, upload_to='cms/branding/'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon class', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='name',
            field=models.CharField(help_text='Internal label', max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(help_text='HTML email body. Use {{variable}} placeholders.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_text',
            field=models.TextField(blank=True, help_text='Plain text fallback'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='rollout_pct',
            field=models.IntegerField(default=100, help_text='0-100% of users who see this feature'),
        ),
        migrations.AlterField(
            model_name='globalseo',
            name='canonical_domain',
            field=models.CharField(blank=True, help_text='e.g. https://yourdomain.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='globalseo',
            name='robots_txt',
            field=models.TextField(default='User-agent: *\nAllow: /\nDisallow: /admin-panel/\nDisallow: /auth/\nDisallow: /creator/\n'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='content',
            field=models.TextField(blank=True, help_text='Body text or custom HTML'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra structured data (stats, FAQs, etc.)'),
        ),
        migrations.AlterField(
            model_name='maintenanceconfig',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Comma-separated IPs that bypass maintenance'),
        ),
        migrations.AlterField(
            model_name='scriptinjection',
            name='load_on_pages',
            field=models.CharField(blank=True, default='*', help_text='* for all pages, or comma-separated URL prefixes', max_length=500),
        ),
        migrations.AlterField(
            model_name='scriptinjection',
            name='script',
            field=models.TextField(help_text='Full <script> tag or raw JS/HTML'),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Additional CSS injected into every page'),
        ),
    ]
