# Generated by Django 6.0.6 on 2026-07-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_brandingconfig_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingconfig',
            name='default_player_banner',
            field=models.ImageField(blank=True, help_text='Fallback background shown in the music player for tracks that have no banner, artist photo, or album cover.', null=True, upload_to='cms/branding/'),
        ),
    ]
