# Generated by Django 4.2.30 on 2026-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0004_couponusage_invoice_alter_coupon_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]