# Generated by Django 4.2.30 on 2026-06-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_image_file_alter_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
