# Generated by Django 4.2.30 on 2026-06-17 07:08

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_imagelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, help_text='External link to the image (used instead of an upload to save storage space).'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.image_orig_path),
        ),
    ]
