# Generated by Django 6.0.6 on 2026-07-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_image_url_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fetch_source',
            field=models.CharField(blank=True, help_text='Where a fetched image came from, e.g. "Pexels".', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='is_fetched',
            field=models.BooleanField(default=False, help_text='True if imported via the admin Fetch Images tool.'),
        ),
    ]
