# Generated by Django 6.0.6 on 2026-07-03 20:05

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_lyrics_lrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Wide banner shown behind the player. If left empty, the artist photo, then album cover, then site default is used automatically.', null=True, upload_to=music.models.track_cover_path),
        ),
        migrations.AddField(
            model_name='track',
            name='fetch_source',
            field=models.CharField(blank=True, help_text='Where a fetched track came from, e.g. "iTunes".', max_length=50),
        ),
        migrations.AddField(
            model_name='track',
            name='is_fetched',
            field=models.BooleanField(default=False, help_text='True if this track was imported via the admin Fetch tool rather than uploaded directly.'),
        ),
    ]
