# Generated by Django 4.2.30 on 2026-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsequence',
            name='trigger',
            field=models.CharField(choices=[('user.registered', 'User Registered'), ('user.subscribed', 'User Subscribed'), ('user.cancelled', 'Subscription Cancelled'), ('content.approved', 'Content Approved'), ('content.rejected', 'Content Rejected'), ('content.uploaded', 'Content Uploaded'), ('payment.completed', 'Payment Completed'), ('payment.failed', 'Payment Failed'), ('withdrawal.requested', 'Withdrawal Requested'), ('withdrawal.approved', 'Withdrawal Approved'), ('creator.milestone', 'Creator Milestone Reached'), ('comment.posted', 'Comment Posted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emailsequencestep',
            name='delay_hours',
            field=models.IntegerField(default=0, help_text='Hours after previous step'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='cron_expr',
            field=models.CharField(blank=True, help_text='Cron expression if interval=custom', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='task_name',
            field=models.CharField(help_text='Dotted task path, e.g. music.tasks.update_trends', max_length=300),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('send_email', 'Send Email'), ('send_notification', 'Send Notification'), ('send_webhook', 'Call Webhook'), ('update_user', 'Update User Field'), ('wait', 'Wait (delay)'), ('condition', 'Conditional Branch')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='config',
            field=models.JSONField(default=dict, help_text='Action-specific configuration'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='trigger_event',
            field=models.CharField(choices=[('user.registered', 'User Registered'), ('user.subscribed', 'User Subscribed'), ('user.cancelled', 'Subscription Cancelled'), ('content.approved', 'Content Approved'), ('content.rejected', 'Content Rejected'), ('content.uploaded', 'Content Uploaded'), ('payment.completed', 'Payment Completed'), ('payment.failed', 'Payment Failed'), ('withdrawal.requested', 'Withdrawal Requested'), ('withdrawal.approved', 'Withdrawal Approved'), ('creator.milestone', 'Creator Milestone Reached'), ('comment.posted', 'Comment Posted')], max_length=50),
        ),
    ]
