# Generated by Django 4.2.30 on 2026-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='source_url',
            field=models.URLField(blank=True, help_text='External link used instead of an upload, to save storage space.'),
        ),
    ]
