# Generated by Django 6.0.6 on 2026-07-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_draft_status'),
        ('content', '0004_content_source_url'),
    ]

    operations = [
    ]
