# Generated by Django 6.0.4 on 2026-04-29 06:29

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.episode_thumb_path),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(upload_to=movies.models.episode_file_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(upload_to=movies.models.movie_thumb_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=movies.models.movie_file_path),
        ),
        migrations.AlterField(
            model_name='series',
            name='thumbnail',
            field=models.ImageField(upload_to=movies.models.series_thumb_path),
        ),
    ]
