# Generated by Django 4.2.30 on 2026-06-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_episode_thumbnail_alter_episode_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
