# Generated by Django 4.2.30 on 2026-06-16 06:32

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movielike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.movie_thumb_path),
        ),
        migrations.AlterField(
            model_name='series',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.series_thumb_path),
        ),
    ]
