# Generated by Django 4.2.30 on 2026-06-17 07:08

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_thumbnail_alter_series_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_url',
            field=models.URLField(blank=True, help_text='External link to the video file (used instead of an upload to save storage space).'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='External link to the video file (used instead of an upload to save storage space).'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=movies.models.episode_file_path),
        ),
    ]
