# Generated by Django 4.2.30 on 2026-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_episode_video_url_movie_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='subtitles',
            field=models.TextField(blank=True, help_text='SRT-format subtitles or plain text transcript.'),
        ),
        migrations.AddField(
            model_name='movie',
            name='subtitles',
            field=models.TextField(blank=True, help_text='SRT-format subtitles or plain text transcript. If empty, AI can generate a scene summary.'),
        ),
    ]
