# Generated by Django 6.0.6 on 2026-07-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_subtitle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fetch_source',
            field=models.CharField(blank=True, help_text='Where a fetched movie came from, e.g. "TMDB".', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_fetched',
            field=models.BooleanField(default=False, help_text='True if this movie was imported via the admin Fetch tool rather than uploaded directly.'),
        ),
    ]
